Fix large literals type inference on 32 bits
goccy/go-yaml pull request #293
Opened 2022-04-29 17:39 UTC by jrisc

Some tests are failing because some large literal integers are meant to be stored on 64 bits, but are stored on 32 on 32 bits architectures. This causes the value to overflow:
```
# github.com/goccy/go-yaml_test [github.com/goccy/go-yaml.test]
./decode_test.go:92:32: cannot use -9223372036854775808 (untyped int constant) as int value in map literal (overflows)
./decode_test.go:112:24: cannot use 4294967296 (untyped int constant) as int value in map literal (overflows)
./encode_test.go:68:24: cannot use 4294967296 (untyped int constant) as int value in map literal (overflows)
```

This commit fixes this issue by using explicit int64 typing.

2022-05-01 04:28 UTC, goccy commented
Could you fix it with a type cast without using temporary variables ?

2022-06-06 04:27 UTC, goccy requested changes
Could you fix it with a type cast without using temporary variables ?

2022-06-07 11:05 UTC, jrisc commented
Sorry about the delay. I replaced variables by type casts.

2022-08-22 12:42 UTC, goccy approved these changes

2022-08-22 12:42 UTC, merged

2022-08-22 12:43 UTC, goccy commented
Thank you for the fixing ! Merged